bench = []
bin = []
example = []
test = []
[badges.maintenance]
status = "none"

[build-dependencies]

[dependencies]

[dev-dependencies]

[features]

[patch]
[profile.release]
panic = "unwind"

[target]

[workspace]
default-members = []
exclude = []
members = ["consensus", "message-broker", "network", "parachain-upgrade", "primitives", "rococo-parachains/", "rococo-parachains/contracts-runtime", "rococo-parachains/pallets/parachain-info", "rococo-parachains/pallets/token-dealer", "rococo-parachains/primitives", "rococo-parachains/runtime", "runtime", "service", "test/runtime", "test/client", "upward-message"]
